mongo:
  host: "localhost"
  port: "27017"
  username: "admin"
  password: "admin"
  
minio:
  endpoint: "127.0.0.1:9000"
  secret-key: "aIJkqHj3syTBtKuLyk6ijaCXwvRNnuVDd3HBGUt3"
  access-key: "9nHluHVlvUzTCh18jLEg"
