mongo:
  host: ${MONGO_HOST}
  port: ${MONGO_PORT}
  username: ${MONGO_USERNAME}
  password: ${MONGO_PASSWORD}
  
minio:
  endpoint: ${MINIO_HOST}
  secret-key: ${MINIO_SECRET_KEY}
  access-key: ${MINIO_ACCESS_KEY}

smtp:
  smtp: ${SMTP_SERVER}
  port: ${SMTP_PORT}
  email: ${SMTP_EMAIL}
  password: ${SMTP_PASSWORD}